//****************************************************************************
// options.inc
//
// Created 6/14/2021 4:59:55 PM by Tim Paterson
//
//****************************************************************************

// Leave option undefined to disable (comment it out)

// Enabling this option eliminates denormal support, saving code size
//.set NO_DENORMALS, 1

// This option extends max angle accepted by trig functions to < 32768 radians.
// Otherwise, the max is 64 * pi, about 201 radians.
//.set WIDE_TRIG_RANGE, 1
